# Hard point mining
CUDA_VISIBLE_DEVICES=0 python main.py data/room/ --workspace trial_ngp_ANR_OHPM_360_room        --hsm --wandb --adaptive_num_rays --ckpt scratch --enable_cam_center --enable_cam_near_far --min_near 0.2 --lambda_tv 0 --lambda_distort 0 --eval_cnt 1 --save_cnt 1 --downscale 4 -O --background random --bound 8
CUDA_VISIBLE_DEVICES=0 python main.py data/bonsai/ --workspace trial_ngp_ANR_OHPM_360_bonsai    --hsm --wandb --adaptive_num_rays --ckpt scratch --enable_cam_center --enable_cam_near_far --min_near 0.2 --lambda_tv 0 --lambda_distort 0 --eval_cnt 1 --save_cnt 1 --downscale 4 -O --background random --bound 8
CUDA_VISIBLE_DEVICES=0 python main.py data/kitchen/ --workspace trial_ngp_ANR_OHPM_360_kitchen  --hsm --wandb --adaptive_num_rays --ckpt scratch --enable_cam_center --enable_cam_near_far --min_near 0.2 --lambda_tv 0 --lambda_distort 0 --eval_cnt 1 --save_cnt 1 --downscale 4 -O --background random --bound 8
CUDA_VISIBLE_DEVICES=0 python main.py data/counter/ --workspace trial_ngp_ANR_OHPM_360_counter  --hsm --wandb --adaptive_num_rays --ckpt scratch --enable_cam_center --enable_cam_near_far --min_near 0.2 --lambda_tv 0 --lambda_distort 0 --eval_cnt 1 --save_cnt 1 --downscale 4 -O --background random --bound 8
CUDA_VISIBLE_DEVICES=0 python main.py data/garden/ --workspace trial_ngp_ANR_OHPM_360_garden    --hsm --wandb --adaptive_num_rays --ckpt scratch --enable_cam_center --enable_cam_near_far --min_near 0.2 --lambda_tv 0 --lambda_distort 0 --eval_cnt 1 --save_cnt 1 --downscale 8 -O --background random --bound 16
CUDA_VISIBLE_DEVICES=0 python main.py data/stump/ --workspace trial_ngp_ANR_OHPM_360_stump      --hsm --wandb --adaptive_num_rays --ckpt scratch --enable_cam_center --enable_cam_near_far --min_near 0.2 --lambda_tv 0 --lambda_distort 0 --eval_cnt 1 --save_cnt 1 --downscale 8 -O --background random --bound 16
CUDA_VISIBLE_DEVICES=0 python main.py data/bicycle/ --workspace trial_ngp_ANR_OHPM_360_bicycle  --hsm --wandb --adaptive_num_rays --ckpt scratch --enable_cam_center --enable_cam_near_far --min_near 0.2 --lambda_tv 0 --lambda_distort 0 --eval_cnt 1 --save_cnt 1 --downscale 8 -O --background random --bound 16

# Baseline 
CUDA_VISIBLE_DEVICES=0 python main.py data/room/ --workspace trial_ngp_ANR_360_room        --wandb --adaptive_num_rays --ckpt scratch --enable_cam_center --enable_cam_near_far --min_near 0.2 --lambda_tv 0 --lambda_distort 0 --eval_cnt 1 --save_cnt 1 --downscale 4 -O --background random --bound 8
CUDA_VISIBLE_DEVICES=0 python main.py data/bonsai/ --workspace trial_ngp_ANR_360_bonsai    --wandb --adaptive_num_rays --ckpt scratch --enable_cam_center --enable_cam_near_far --min_near 0.2 --lambda_tv 0 --lambda_distort 0 --eval_cnt 1 --save_cnt 1 --downscale 4 -O --background random --bound 8
CUDA_VISIBLE_DEVICES=0 python main.py data/kitchen/ --workspace trial_ngp_ANR_360_kitchen  --wandb --adaptive_num_rays --ckpt scratch --enable_cam_center --enable_cam_near_far --min_near 0.2 --lambda_tv 0 --lambda_distort 0 --eval_cnt 1 --save_cnt 1 --downscale 4 -O --background random --bound 8
CUDA_VISIBLE_DEVICES=0 python main.py data/counter/ --workspace trial_ngp_ANR_360_counter  --wandb --adaptive_num_rays --ckpt scratch --enable_cam_center --enable_cam_near_far --min_near 0.2 --lambda_tv 0 --lambda_distort 0 --eval_cnt 1 --save_cnt 1 --downscale 4 -O --background random --bound 8
CUDA_VISIBLE_DEVICES=0 python main.py data/garden/ --workspace trial_ngp_ANR_360_garden    --wandb --adaptive_num_rays --ckpt scratch --enable_cam_center --enable_cam_near_far --min_near 0.2 --lambda_tv 0 --lambda_distort 0 --eval_cnt 1 --save_cnt 1 --downscale 8 -O --background random --bound 16
CUDA_VISIBLE_DEVICES=0 python main.py data/stump/ --workspace trial_ngp_ANR_360_stump      --wandb --adaptive_num_rays --ckpt scratch --enable_cam_center --enable_cam_near_far --min_near 0.2 --lambda_tv 0 --lambda_distort 0 --eval_cnt 1 --save_cnt 1 --downscale 8 -O --background random --bound 16
CUDA_VISIBLE_DEVICES=0 python main.py data/bicycle/ --workspace trial_ngp_ANR_360_bicycle  --wandb --adaptive_num_rays --ckpt scratch --enable_cam_center --enable_cam_near_far --min_near 0.2 --lambda_tv 0 --lambda_distort 0 --eval_cnt 1 --save_cnt 1 --downscale 8 -O --background random --bound 16
